apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: database
  namespace: postgres

spec:
   replicas: 2
   image: postgres:12

   database:
      size: 1Gi
      storageClassName: do-block-storage

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword

