repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis-release
    chart: bitnami/redis
    namespace: redis
    createNamespace: true
    values:
      - master.service.port: 6379
      - auth.enabled: true
      - auth.password: <YOUR_REDIS_PASSWORD>
      - replica.replicaCount: 1
      - global.storageClass: do-block-storage
